// swift-tools-version:5.3

// This file was autogenerated, do not modify

import PackageDescription

let package = Package(
    name: "EpaySDK",
    defaultLocalization: "ru",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            name: "EpaySDK",
            targets: ["EpaySDK"]
        ),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "EpaySDK",
            dependencies: [],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
